apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secret
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUsername: {{ .Values.auth.rootUsername | quote }}
  rootPassword: {{ .Values.auth.rootPassword | quote }}
